const COMPANY_INFO = {
  COST:  { name: 'Costco Wholesale Corp.', next: 'Q3 2026', date: 'May 29, 2026 AMC' },
  MSFT:  { name: 'Microsoft Corporation',  next: 'Q3 FY2026', date: 'Apr 30, 2026 AMC' },
  AMZN:  { name: 'Amazon.com Inc.',         next: 'Q1 2026', date: 'May 1, 2026 AMC' },
  GOOGL: { name: 'Alphabet Inc.',           next: 'Q1 2026', date: 'Apr 29, 2026 AMC' },
  NVDA:  { name: 'NVIDIA Corporation',      next: 'Q1 FY2027', date: 'May 28, 2026 AMC' },
  META:  { name: 'Meta Platforms Inc.',     next: 'Q1 2026', date: 'Apr 30, 2026 AMC' },
  GLW:   { name: 'Corning Incorporated',    next: 'Q2 2026', date: 'Jul 29, 2026 AMC' },
  TSM:   { name: 'Taiwan Semiconductor',    next: 'Q2 2026', date: 'Jul 17, 2026' },
  AAPL:  { name: 'Apple Inc.',              next: 'Q2 FY2026', date: 'May 1, 2026 AMC' },
};
const DEFAULT_WATCHLIST = ['COST', 'MSFT', 'AMZN'];
function getWatchlist() { const raw = localStorage.getItem('watchlist'); return raw ? JSON.parse(raw) : [...DEFAULT_WATCHLIST]; }
function saveWatchlist(list) { localStorage.setItem('watchlist', JSON.stringify(list)); }
function addTicker(ticker) { ticker = ticker.toUpperCase().trim(); if (!ticker) return 'Please enter a ticker symbol.'; const list = getWatchlist(); if (list.includes(ticker)) return ticker + ' is already on your watchlist.'; list.push(ticker); saveWatchlist(list); return null; }
function removeTicker(ticker) { const list = getWatchlist().filter(t => t !== ticker); saveWatchlist(list); }
function renderSidebarWatchlist(active) { const el = document.getElementById('sidebar-wl-links'); if (!el) return; const list = getWatchlist(); el.innerHTML = list.map(t => { const a = t === active ? ' class="active"' : ''; return '<li><a href="company.html?t=' + t + '"' + a + '>' + t + '</a></li>'; }).join(''); }
function renderWatchlistCards() { const grid = document.getElementById('watchlist-grid'); if (!grid) return; const list = getWatchlist(); if (!list.length) { grid.innerHTML = '<p style="color:#aaa;font-size:13px;grid-column:1/-1">Your watchlist is empty. Add a ticker below.</p>'; return; } grid.innerHTML = list.map(t => { const info = COMPANY_INFO[t] || { name: t, next: '—', date: '—' }; return '<div class="wl-card" id="card-' + t + '"><button class="wl-remove" onclick="handleRemove(\'' + t + '\')">&times;</button><div class="wl-ticker">' + t + '</div><div class="wl-name">' + info.name + '</div><div class="wl-row">Next earnings: <span>' + info.next + '</span></div><div class="wl-row">Reports: <span>' + info.date + '</span></div><div class="wl-links"><a class="wl-link" href="preview-googl.html">Preview</a><a class="wl-link" href="financials-googl.html">Financials</a><a class="wl-link" href="review-googl.html">Review</a></div></div>'; }).join(''); }
function handleRemove(ticker) { removeTicker(ticker); renderWatchlistCards(); renderSidebarWatchlist(); }
function handleAddForm() { const input = document.getElementById('ticker-input'); const msg = document.getElementById('add-msg'); if (!input) return; const err = addTicker(input.value); if (err) { msg.textContent = err; } else { msg.textContent = ''; input.value = ''; renderWatchlistCards(); renderSidebarWatchlist(); } }
function initTabs() { const btns = document.querySelectorAll('.tab-btn'); const panels = document.querySelectorAll('.tab-panel'); if (!btns.length) return; btns.forEach(btn => { btn.addEventListener('click', () => { btns.forEach(b => b.classList.remove('active')); panels.forEach(p => p.classList.remove('active')); btn.classList.add('active'); const target = document.getElementById(btn.dataset.tab); if (target) target.classList.add('active'); }); }); }
function drawBarChart(containerId, bars) { const container = document.getElementById(containerId); if (!container) return; const W = 420, H = 180, PAD = { top: 20, right: 20, bottom: 36, left: 44 }; const chartW = W - PAD.left - PAD.right; const chartH = H - PAD.top - PAD.bottom; const maxVal = Math.max(...bars.map(b => b.value)) * 1.15; const barW = Math.min(52, (chartW / bars.length) * 0.55); const spacing = chartW / bars.length; let gridLines = '', gridLabels = ''; for (let i = 0; i <= 4; i++) { const y = PAD.top + chartH - (i / 4) * chartH; const val = ((i / 4) * maxVal).toFixed(1); gridLines += '<line x1="' + PAD.left + '" y1="' + y + '" x2="' + (W - PAD.right) + '" y2="' + y + '" stroke="#f0f0ec" stroke-width="1"/>'; gridLabels += '<text x="' + (PAD.left - 6) + '" y="' + (y + 4) + '" text-anchor="end" font-size="9" fill="#bbb">' + val + '</text>'; } let barsSVG = ''; bars.forEach((b, i) => { const barH = (b.value / maxVal) * chartH; const x = PAD.left + i * spacing + (spacing - barW) / 2; const y = PAD.top + chartH - barH; barsSVG += '<rect x="' + x + '" y="' + y + '" width="' + barW + '" height="' + barH + '" fill="' + b.color + '" rx="2"/><text x="' + (x + barW / 2) + '" y="' + (y - 5) + '" text-anchor="middle" font-size="10" fill="#555">' + b.displayValue + '</text><text x="' + (x + barW / 2) + '" y="' + (PAD.top + chartH + 16) + '" text-anchor="middle" font-size="10" fill="#888">' + b.label + '</text>'; }); const axes = '<line x1="' + PAD.left + '" y1="' + PAD.top + '" x2="' + PAD.left + '" y2="' + (PAD.top + chartH) + '" stroke="#ddd" stroke-width="1"/><line x1="' + PAD.left + '" y1="' + (PAD.top + chartH) + '" x2="' + (W - PAD.right) + '" y2="' + (PAD.top + chartH) + '" stroke="#ddd" stroke-width="1"/>'; container.innerHTML = '<svg viewBox="0 0 ' + W + ' ' + H + '" width="100%" style="max-width:' + W + 'px;display:block;">' + gridLines + gridLabels + axes + barsSVG + '</svg>'; }
document.addEventListener('DOMContentLoaded', () => { renderSidebarWatchlist(); renderWatchlistCards(); initTabs(); const addBtn = document.getElementById('add-btn'); if (addBtn) { addBtn.addEventListener('click', handleAddForm); document.getElementById('ticker-input')?.addEventListener('keydown', e => { if (e.key === 'Enter') handleAddForm(); }); } if (document.getElementById('guide-chart')) { drawBarChart('guide-chart', [{ label: 'Q1 Guide', value: 10.8, color: '#d4a017', displayValue: '$10.8B' }, { label: 'Q1 Actual', value: 11.4, color: '#2d7a2d', displayValue: '$11.4B' }, { label: 'Q2 Guide', value: 11.7, color: '#2c5f8a', displayValue: '$11.7B' }]); } if (document.getElementById('springboard-chart')) { drawBarChart('springboard-chart', [{ label: '2023 Base', value: 12.8, color: '#ccc', displayValue: '$12.8B' }, { label: 'Orig. Target', value: 20.8, color: '#d4a017', displayValue: '+$8B' }, { label: 'Upg. Target', value: 23.8, color: '#2d7a2d', displayValue: '+$11B' }, { label: '2026 Plan', value: 19.3, color: '#2c5f8a', displayValue: '+$6.5B' }]); } const showMoreBtn = document.getElementById('show-more-btn'); const hiddenCards = document.querySelectorAll('.news-card.hidden-card'); if (showMoreBtn && hiddenCards.length) { showMoreBtn.addEventListener('click', e => { e.preventDefault(); const open = showMoreBtn.dataset.open === 'true'; hiddenCards.forEach(c => c.style.display = open ? 'none' : 'flex'); showMoreBtn.textContent = open ? 'Show all 8 articles ↓' : 'Hide extra articles ↑'; showMoreBtn.dataset.open = (!open).toString(); }); } });